version: "3.8"

name: bingo-prod

services:
  frontend:
    image: your-dockerhub-username/bingo-frontend:latest
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    restart: always
    depends_on:
      - backend

  backend:
    image: your-dockerhub-username/bingo-backend:latest
    expose:
      - "8080"
    environment:
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}          # cloud postgres URL
      - GRAPHQL_ENDPOINT=${GRAPHQL_ENDPOINT}
      - FRONTEND_URL=${FRONTEND_URL}
      - REDIS_HOST=${REDIS_HOST}              # cloud redis hostname
      - REDIS_PORT=${REDIS_PORT}              # cloud redis port
      - REDIS_PASSWORD=${REDIS_PASSWORD}      # redis password
    restart: always

  redis-workers:
    image: your-dockerhub-username/bingo-redis-workers:latest
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: always
    depends_on:
      - backend

volumes: {}