version: "3.8"

name: bingo
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_CALLBACK_URL=http://localhost:8080/auth/google/callback
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
      - JWT_SECRET=mysecretkey
      - DATABASE_URL=postgres://postgres:mysecretpassword@postgres:5432/mydatabase
      - GRAPHQL_ENDPOINT=http://localhost:8080/graphql
      - FRONTEND_URL=http://localhost:3000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
  redis-workers:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.redis-workers
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=mydatabase

    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local
