version: "3.8"

name: bingo
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.frontend
    ports:
      - "3000:3000"
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.backend
    ports:
      - "8080:8080"
    env_file:
      - ./.env
  redis-workers:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.redis-workers
    env_file:
      - ./.env
