export default function HowToPlay() {
  return (
    <div className="bg-gray-800 border border-gray-500/25 p-6 rounded-lg shadow-lg w-full h-full">
      <h2 className="text-2xl font-bold mb-4 text-gray-100">How to Play</h2>
      <p className="text-gray-300">Game instructions and rules go here.</p>
      <p className="text-gray-300">
        Lorem, ipsum dolor sit amet consectetur adipisicing elit. Soluta, harum id! Consequatur odit ut tempore, architecto deleniti eligendi perspiciatis laborum ex accusamus, praesentium dolorem explicabo aspernatur, non optio neque ducimus accusantium est magnam sequi quia. Odio et ullam commodi velit impedit incidunt ratione, voluptas dicta neque eligendi animi tempore illum eaque voluptatum aliquid tempora tenetur necessitatibus veniam suscipit debitis id iste ut quas! Maxime doloremque illo sint necessitatibus. Blanditiis nemo reprehenderit beatae, laboriosam perspiciatis quo recusandae, adipisci corrupti voluptatum iure aliquam explicabo ipsa obcaecati velit quod harum repellendus omnis? Beatae, molestias quasi cum delectus maxime quis. Commodi vero excepturi, similique recusandae, fuga architecto labore itaque consequuntur hic corrupti quas natus corporis explicabo assumenda expedita. Quam, voluptas porro veritatis neque repellat vel vero adipisci a voluptates in ut praesentium ipsam velit dicta minima. Ut eveniet deleniti soluta veniam, enim nihil eaque modi temporibus cum pariatur unde! Recusandae, consequatur ab, ipsam adipisci facilis beatae quae quidem tempora, minima distinctio deserunt delectus odio nihil voluptatum nemo praesentium ratione consectetur. Consequuntur ab nam officia laborum soluta dignissimos, inventore aut a mollitia cum accusantium ipsa magni, corporis blanditiis facere obcaecati laboriosam placeat veniam vitae dolores nulla sapiente? Debitis voluptates voluptatem commodi voluptatum dolor quos doloremque distinctio et earum culpa cumque iusto quidem, tempora in facere error non adipisci, libero fuga praesentium ipsum? Laborum nulla accusamus sed molestiae minima, mollitia molestias a? Magnam temporibus eum iste nemo fugit magni ab obcaecati culpa ipsum vel veniam deleniti at dignissimos odio aut voluptatem, voluptatum tenetur quae aspernatur. Pariatur eligendi laudantium autem modi id, commodi sed veniam error. Nihil molestias voluptas voluptate, sequi omnis esse labore delectus architecto voluptates fugit dolores ex illum blanditiis vero accusamus provident pariatur maxime amet exercitationem sunt ipsa obcaecati assumenda cupiditate sint. Expedita, quas fuga iure aperiam veritatis minima neque maiores aliquid explicabo dolorem adipisci animi repellendus, tempora mollitia suscipit assumenda quasi reiciendis delectus asperiores?
      </p>
    </div>
  );
}

